# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
    ]
